# Use deowullf/Andrey159753 as user/password credentials

web:
  image: nginx:latest
  volumes: ./rep1-zd1/pr_mysql_wp_nginx/templates
  ports: "8080:80"
 environment:
  NGINX_HOST=foobar.com
  NGINX_PORT=80

version: '2.2'
services:
 wordpress:
  image: wordpress
  restart: always
  ports:
   8080:80
  environment:
   WORDPRESS_DB_HOST: db
   WORDPRESS_DB_USER: exampleuser
   WORDPRESS_DB_PASSWORD: examplepass
   WORDPRESS_DB_NAME: exampledb
 volumes:
  wordpress:/var/www/html

 db:
  image: mysql
  restart: always
  environment:
  MYSQL_DATABASE: exampledb
  MYSQL_USER: exampleuser
  MYSQL_PASSWORD: examplepass
  MYSQL_RANDOM_ROOT_PASSWORD: '1'
 volumes:
  ./rep1-zd1/pr_mysql_wp_nginx
  db_data:/rep1-zd1/pr_mysql_wp_nginx/mysql

 volumes:
  wordpress:
  db:
 